### ISSUE TITLE
A question about choice the Grad Mask Ratio.

### ISSUE THREAD

**Issue by mmwan101010** [jhcknzzm/Federated-Learning-Backdoor#10]
when i reproduce the experiments, i found different have different results and the accuracy rate not increases as the  Grad Mask Ratio increases or the  Grad Mask Ratio deduce.
Is there no accurate Grad Mask Ratio to ensure that the accuracy of this parameter will be high.
Or, the relationship between Grad Mask Ratio size and accuracy is not a simple linear relationship, which requires multiple experiments to obtain the best Grad Mask Ratio with high accuracy?

looking forward for your replay.
Have a good day.

**Comment by jhcknzzm** [comment]
When you mentioned the accuracy rate, do you mean the backdoor accuracy? In the process of attacker participating in FL, under the condition of fixed attack times (AttackNum) and attacker's learning rate, the smaller the Mask Ratio, the lower the attack efficiency, and the larger the Mask Ratio, the easier the backdoor accuracy is to rise to 100%. However, the Lifespan of the backdoor does not have a monotonic relationship with the Mask Ratio. If you want to maximize the Lifespan, you need to choose a suitable Mask Ratio and AttackNum or learning rate.

**Comment by mmwan101010** [comment]
thanks for your replay
