### ISSUE TITLE
Corpus parsed dataset seems to have expired

### ISSUE THREAD

**Issue by cjrcjrdl1** [jhcknzzm/Federated-Learning-Backdoor#18]
Thank you for providing us with a good code.

The link in Corpus parsed dataset seems to have expired at this time.

Can you upload it again?

Or can you tell me how to make a corpus_80000.pt.tar??

**Comment by zalmanchen** [comment]
hi, I also meet the same question, have you solved it?

**Comment by cjrcjrdl1** [comment]
> hi, I also meet the same question, have you solved it?

https://github.com/ebagdasa/backdoor_federated_learning/issues/21

It will help you if you refer to this
