### ISSUE TITLE
recurrent problem : unrecognized arguments: -same_structure --lastwords 1

### ISSUE THREAD

**Issue by mmwan101010** [jhcknzzm/Federated-Learning-Backdoor#7]
when i recurrent this, i meet some problem like that
I am not sure why,could u please help me ?
`(neurotoxin) X:\Directory\code\neurotoxin\FL_Backdoor_NLP>python main_training.py --params utils/words_reddit_lstm.yaml --run_name Reddit_LSTM_SentenceId0  --GPU_id 1  --gradmask_ratio 1.0  --start_epoch 1 --PGD 0  --semantic_target True --same_structure True --defense True --s_norm 3.0  --sentence_id_list 0 --lastwords 1
Start training ------
usage: main_training.py [-h] [--params PARAMS] [--GPU_id GPU_ID] [--is_poison IS_POISON] [--run_name RUN_NAME] [--poison_lr POISON_LR] [--start_epoch START_EPOCH] [--aggregate_all_layer AGGREGATE_ALL_LAYER]
                        [--run_slurm RUN_SLURM] [--same_structure SAME_STRUCTURE] [--num_middle_token_same_structure NUM_MIDDLE_TOKEN_SAME_STRUCTURE] [--semantic_target SEMANTIC_TARGET] [--defense DEFENSE]
                        [--diff_privacy DIFF_PRIVACY] [--s_norm S_NORM] [--PGD PGD] [--attack_num ATTACK_NUM] [--gradmask_ratio GRADMASK_RATIO] [--sentence_id_list SENTENCE_ID_LIST [SENTENCE_ID_LIST ...]]
main_training.py: error: unrecognized arguments: --lastwords 1`

**Comment by jhcknzzm** [comment]
Oh, please remove the --lastwords 1 in the command, which is not used in the code

**Comment by mmwan101010** [comment]
> Oh, please remove the --lastwords 1 in the command, which is not used in the code

Thank you for your replay ,  : )
